In [1]:
import numpy as np


In [2]:
food = np.array(["Pakora","Samosha","Chat"])

In [3]:
food

array(['Pakora', 'Samosha', 'Chat'], dtype='<U7')

In [4]:
type(food)

numpy.ndarray

In [5]:
len(food)

3

In [6]:
price = np.array([5,5,5])

In [7]:
price

array([5, 5, 5])

In [8]:
food[0]

'Pakora'

In [9]:
price.mean()

5.0

In [10]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [15]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0,100,num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [29]:
np.ones(6,dtype=np.int8)

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
np.ones(6,dtype=np.float64)

array([1., 1., 1., 1., 1., 1.])

# Array function

In [31]:
a = np.array([[1,1,1,1],[2,2,2,2]])
a

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [25]:
b = np.array([[3,3,3,3],[4,4,4,4]])
b

array([[3, 3, 3, 3],
       [4, 4, 4, 4]])

In [27]:
np.concatenate((a,b),axis = 0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [28]:
np.concatenate((a,b),axis = 1)

array([[1, 1, 1, 1, 3, 3, 3, 3],
       [2, 2, 2, 2, 4, 4, 4, 4]])

In [32]:
b.ndim

2

In [33]:
#size number of element 
b.size

8

In [34]:
#shape
b.shape

(2, 4)

In [35]:
a1 = np.arange(9)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
b = a1.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.reshape(a1,newshape=(1,9),order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [39]:
#convert 1D to 2 D
a1.shape

(9,)

In [40]:
b = a1[np.newaxis,:]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [41]:
b.shape

(1, 9)

In [43]:
b.mean()

4.0